<question> := <filter> |
              <phrase>;

<filter> := <number-simple-filter> |
            <date-simple-filter> |
            <date-complex-filter> |
            <string-simple-filter> |
            <bool-function-column>;

<phrase> := <top-n> |
            <bottom-n> |
            <sort-by> |
            <all-columns> |
            <formula-column>;

<number-simple-filter> := <number-columns> <bool-symbol> <number> |
                          <number> <bool-symbol> <number-columns> |
                          <number-columns> <bool-symbol> <number-columns> |
                          <number> <bool-symbol> <number>;

<date-simple-filter> := <date-columns> <bool-symbol> <column-value> |
                        <column-value> <bool-symbol> <number-columns> |
                        <date-columns> <bool-symbol> <date-columns> |
                        <column-value> <bool-symbol> <column-value>;

<date-complex-filter> := <before-after-filter> |
                         <last-filter>;

<string-simple-filter> := <all-string-column> 等于 <column-value> |
                          <all-string-column> = <column-value>;

<top-n> := 前 <integer> <number-columns>;

<bottom-n> := 倒数 <integer> <number-columns>;

<sort-by> := 按 <all-columns> 升序 |
             按 <all-columns> 降序 |
             按 <all-columns> 排序;

<before-after-filter> := <before-filter> |
                         <after-filter>;

<before-chinese> := 之前 |
                    之前的 |
                    以前 |
                    以前的;

<before-filter> := 在 <date-columns> <before-chinese> |
                   <date-columns> <before-chinese> |
                   在 <column-value> <before-chinese> |
                   <column-value> <before-chinese> |
                   <all-date-column> 在 <date-columns> <before-chinese> |
                   <all-date-column> 在 <column-value> <before-chinese>;

<after-chinese> := 之后 |
                   之后的 |
                   以后 |
                   以后的;

<after-filter> := 在 <date-columns> <after-chinese> |
                  <date-columns> <after-chinese> |
                  在 <column-value> <after-chinese> |
                  <column-value> <after-chinese> |
                  <all-date-column> 在 <date-columns> <after-chinese> |
                  <all-date-column> 在 <column-value> <after-chinese>;

<last-filter> := <last-days-filter> |
                 <last-weeks-filter> |
                 <last-months-filter> |
                 <last-quarters-filter> |
                 <last-years-filter>;

<last-chinese> := 过去 |
                  前 |
                  最近 |
                  近;

<last-days-chinese> := 天 |
                       天的;
<last-days-filter> := <last-chinese> <integer> <last-days-chinese> |
                      <all-date-column> <last-chinese> <integer> <last-days-chinese>;

<last-weeks-chinese> := 周 |
                        周的 |
                        星期 |
                        星期的 |
                        个星期 |
                        个星期的;
<last-weeks-filter> := <last-chinese> <integer> <last-weeks-chinese> |
                       <all-date-column> <last-chinese> <integer> <last-weeks-chinese>;

<last-months-chinese> := 月 |
                         月的 |
                         个月 |
                         个月的;
<last-months-filter> := <last-chinese> <integer> <last-months-chinese> |
                        <all-date-column> <last-chinese> <integer> <last-months-chinese>;

<last-quarters-chinese> := 季度 |
                           季度的 |
                           季 |
                           季的 |
                           个季 |
                           个季的 |
                           个季度的 |
                           个季度的;
<last-quarters-filter> := <last-chinese> <integer> <last-quarters-chinese> |
                          <all-date-column> <last-chinese> <integer> <last-quarters-chinese>;

<last-years-chinese> := 年 |
                        年的;
<last-years-filter> := <last-chinese> <integer> <last-years-chinese> |
                       <all-date-column> <last-chinese> <integer> <last-years-chinese>;

<all-columns> := <number-columns> |
                 <string-columns> |
                 <bool-columns> |
                 <date-columns>;

<number-columns> := <all-int-column> |
                    <all-double-column>;

<string-columns> := <all-string-column>;

<bool-columns> := <all-bool-column>;

<date-columns> := <all-date-column>;

<all-int-column> := <int-column> |
                    <table-int-column>;

<all-double-column> := <double-column> |
                       <table-double-column>;

<all-string-column> := <string-column> |
                       <table-string-column>;

<all-bool-column> := <bool-column> |
                     <table-bool-column>;

<all-date-column> := <date-column> |
                     <table-date-column>;

<all-source-column> := <number-source-column> |
                       <all-string-column> |
                       <all-bool-column> |
                       <all-date-column>;

<number-source-column> := <all-int-column> |
                          <all-double-column>;

<bool-symbol> := 大于 | 小于 | 不小于 | 大于等于 | 不大于 | 小于等于 | 等于 | 不等于 | > | < | >= | <= | = | !=;
<math-symbol> := + | - | * | / | ^;
<number> := <integer> |
            <double>;
<integer> := 1;
<double> := 1;

<column-value> := <double-quote-column-value> |
                  <single-quote-column-value> |
                  <double-quote-column-value> , <column-value> |
                  <single-quote-column-value> , <column-value>;

<double-quote-column-value> := " <value> ";
<single-quote-column-value> := ' <value> ';
<value> := 1;
