<date-function-column> := <to_date-function> |
                          <date-function> |
                          <add-days-function> |
                          <start-of-month-function> |
                          <start-of-quarter-function> |
                          <start-of-week-function> |
                          <start-of-year-function>;

<to_date-function> := to_date ( <number-columns> ) |
                      to_date ( <number> );

<add-days-function> := add_days ( <all-date-column> , <integer> ) |
                       add_days ( <date-string-value> , <integer> );

<date-function> := date ( <all-date-column> ) |
                   date ( <date-string-value> );


<start-of-month-function> := start_of_month ( <all-date-column> ) |
                             start_of_month ( <date-string-value> );


<start-of-quarter-function> := start_of_quarter ( <all-date-column> ) |
                               start_of_quarter ( <date-string-value> );


<start-of-week-function> := start_of_week ( <all-date-column> ) |
                            start_of_week ( <date-string-value> );


<start-of-year-function> := start_of_year ( <all-date-column> ) |
                            start_of_year ( <date-string-value> );




