<question> := <phrase-or-filter>;

<phrase-or-filter> := <phrase> |
                      <filter>;

<phrase> := <top-n> <int-measure-column> |
            <bottom-n> <int-measure-column>;

<top-n> := top <integer> |
           top;

<bottom-n> := bottom <integer> |
           bottom;

<filter> := <simple-filter> |
            <number-keyword-filter>;

<simple-filter> := <int-measure-column> <bool-symbol> <number>;

<number-keyword-filter> := <number-keyword> <bool-symbol> <number>;

<number-keyword> ::= sum <measure-column> |
                     average <measure-column>;

<measure-column> := <int-measure-column> |
                    <float-measure-column>;

<bool-symbol> := > | < | = | !=;
<integer> := 1;
<number> := 1;
