<year-to-date> :=
     本年截至目前 |
     本年截至目前的 |
     本年截至目前为止 |
     本年截至目前为止的 |
     本年 |
     当年 |
     今年;

<quarter-to-date> ::=
  本季度截至目前 |
  本季度截至目前的 |
  本季度截至目前为止 |
  本季度截至目前为止的 |
  当季度截至目前 |
  本季度;