<question> := <number-function>;
<number-function> := <add> | <sub> | - <number-function> | <integer> | ( <number-function> );
<add> := <integer> + <number-function>;
<sub> := <integer> - <number-function>;
<integer> := 1;